# Form implementation generated from reading ui file 'C:\Users\hp\Documents\Python_Scripts\Pyqt_programme\modele_binomial_secour.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from option import *
from trinomialmodel import *
from Binomialamericaine import *
from Trinomialamericain import *
from les_grecques import *
from binomialgeneralise import*
from binomialflexible import *
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 555)
        MainWindow.setStyleSheet("*{\n"
"border:none;\n"
"background-color: transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"\n"
"\n"
"}\n"
"\n"
"#mainmenu{\n"
"    background-color: cyan;\n"
"border:2px solid;\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color: white;\n"
"}\n"
"#subsidebar{\n"
"background-color:#16191d;\n"
"}\n"
"#widget_4{\n"
"background-color:#16191d;\n"
"}\n"
"\n"
"#subsidebar QPushButton{\n"
"text-align: left;\n"
"padding:2px 5px;\n"
"color:#fff;\n"
"}\n"
"#subsidebar QPushButton :hover{\n"
"padding:2px 5px;\n"
"background-color:cyan;\n"
"}\n"
"\n"
"#page_3{\n"
"background-color: white;\n"
"border:2px solid ;\n"
"}\n"
"\n"
"#page_2{\n"
"background-color: white;\n"
"border:2px solid ;\n"
"}\n"
"\n"
"#page{\n"
"background-color: white;\n"
"border:2px solid ;\n"
"}\n"
"\n"
"#lineEdit_3{\n"
"border-radius: 3px;\n"
"border: 2px solid #000;\n"
"}\n"
"#widget_2{\n"
"border:2px solid gray;\n"
"border-radius: 5px;\n"
"background:#b7ffe1;\n"
"}\n"
"#widget_3{\n"
"border:2px solid gray;\n"
"border-radius: 5px;\n"
"background:lightcyan;\n"
"}\n"
"\n"
"#widget_8{\n"
"background-color: #aaffff;\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_10{\n"
"background-color: #55ff7f;\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"#widget_7{\n"
"background-color: #DDD;\n"
"border: 2px solid #000;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_9{\n"
"background-color: lightcyan;\n"
"border: 2px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_15{\n"
"background-color:lightcyan;\n"
"border: 2px solid ;\n"
"border-radius: 5px;\n"
"}\n"
"#widget_11{\n"
"background-color: rgb(235, 157, 235);\n"
"border: 2px solid ;\n"
"border-radius:5px;\n"
"}\n"
"#widget_17{\n"
"border: 2px solid gray ;\n"
"border-radius:5px;\n"
"background-color: #675cff;\n"
"}\n"
"#widget_19{\n"
"border-style: ;\n"
"border: 2px groove gray ;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#widget_21{\n"
"border: 2px groove gray ;\n"
"border-radius:5px;\n"
"}\n"
"#widget_20{\n"
"background-color:lightcyan;\n"
"border: 1px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_22{\n"
"background-color: lightcyan;\n"
"border: 1px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_26{\n"
"background-color: lightcyan;\n"
"border: 1px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_6{\n"
"border: 2px groove gray ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_18{\n"
"border: 2px groove gray ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_25{\n"
"border: 2px groove gray ;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#widget_12{\n"
"background-color: lightcyan;\n"
"border: 2px solid l;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}\n"
"\n"
"#widget_27{\n"
"background-color: lightcyan;\n"
"border: 1px solid ;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"#widget_14{\n"
"background-color: #FFE436;\n"
"border: 2px solid ;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}\n"
"\n"
"#home_1{\n"
"border: 2px solid black ;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}\n"
"#label_43{\n"
"border: 2px solid black ;\n"
"border-top:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subsidebar = QtWidgets.QWidget(parent=self.sidebar)
        self.subsidebar.setObjectName("subsidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subsidebar)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.subsidebar)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu = QtWidgets.QPushButton(parent=self.frame)
        self.menu.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"\n"
"}")
        self.menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/menu.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.menu.setIcon(icon)
        self.menu.setObjectName("menu")
        self.verticalLayout_3.addWidget(self.menu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_2 = QtWidgets.QFrame(parent=self.subsidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.home = QtWidgets.QPushButton(parent=self.frame_2)
        self.home.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color:#38a7a7;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/home.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.home.setIcon(icon1)
        self.home.setObjectName("home")
        self.home.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        self.verticalLayout_4.addWidget(self.home)
        self.optimization = QtWidgets.QPushButton(parent=self.frame_2)
        self.optimization.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color:#38a7a7;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/settings.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.optimization.setIcon(icon2)
        self.optimization.setObjectName("optimization")
        self.optimization.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page))
        self.verticalLayout_4.addWidget(self.optimization)
        self.contact = QtWidgets.QPushButton(parent=self.frame_2)
        self.contact.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color:#38a7a7;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/grid.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.contact.setIcon(icon3)
        self.contact.setObjectName("contact")
        self.contact.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_3))
        self.verticalLayout_4.addWidget(self.contact)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(parent=self.subsidebar)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.deconnect = QtWidgets.QPushButton(parent=self.frame_3)
        self.deconnect.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/log-out.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.deconnect.setIcon(icon4)
        self.deconnect.setObjectName("deconnect")
        self.verticalLayout_5.addWidget(self.deconnect)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.subsidebar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.sidebar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.mainmenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainmenu.setObjectName("mainmenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainmenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.mainmenu)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(13)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainmenu)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_19 = QtWidgets.QWidget(parent=self.page)
        self.widget_19.setMinimumSize(QtCore.QSize(570, 114))
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_20 = QtWidgets.QWidget(parent=self.widget_19)
        self.widget_20.setMaximumSize(QtCore.QSize(270, 30))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_10.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_20)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/target.svg"))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_20)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.verticalLayout_19.addWidget(self.widget_20, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_19)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_63 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_63.setObjectName("label_63")
        self.gridLayout_4.addWidget(self.label_63, 1, 0, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(parent=self.widget_2)
        self.doubleSpinBox_9.setMaximum(1.0)
        self.doubleSpinBox_9.setSingleStep(0.01)
        #self.doubleSpinBox_9.setSuffix()
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_4.addWidget(self.doubleSpinBox_9, 1, 6, 1, 1)
        self.label_65 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_65.setObjectName("label_65")
        self.gridLayout_4.addWidget(self.label_65, 1, 7, 1, 1)
        self.label_55 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_4.addWidget(self.label_55, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_4.addWidget(self.label_57, 0, 7, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(parent=self.widget_2)
        self.doubleSpinBox_7.setMaximumSize(QtCore.QSize(111, 18))
        self.doubleSpinBox_7.setMaximum(1000)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_4.addWidget(self.doubleSpinBox_7, 0, 8, 1, 2)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(parent=self.widget_2)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_6.setMaximum(1000)
        self.gridLayout_4.addWidget(self.doubleSpinBox_6, 0, 6, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(parent=self.widget_2)
        self.doubleSpinBox_10.setMaximumSize(QtCore.QSize(111, 18))
        self.doubleSpinBox_10.setSuffix('an(s)')
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_4.addWidget(self.doubleSpinBox_10, 1, 8, 1, 2)
        self.label_56 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 0, 3, 1, 1)
        self.label_64 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_64.setObjectName("label_64")
        self.gridLayout_4.addWidget(self.label_64, 1, 3, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.widget_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(parent=self.widget_2)
        self.doubleSpinBox_8.setMaximum(1.0)
        self.doubleSpinBox_8.setSingleStep(0.01)
        #self.doubleSpinBox_8.setSuffix()
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_4.addWidget(self.doubleSpinBox_8, 1, 1, 1, 1)
        self.verticalLayout_19.addWidget(self.widget_2)
        self.verticalLayout_22.addWidget(self.widget_19)
        self.widget_21 = QtWidgets.QWidget(parent=self.page)
        self.widget_21.setMinimumSize(QtCore.QSize(570, 188))
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_22 = QtWidgets.QWidget(parent=self.widget_21)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_11.setContentsMargins(3, 2, 3, 1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_32 = QtWidgets.QLabel(parent=self.widget_22)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/settings.svg"))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_34 = QtWidgets.QLabel(parent=self.widget_22)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_11.addWidget(self.label_34, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_20.addWidget(self.widget_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_21)
        self.widget_3.setMinimumSize(QtCore.QSize(552, 112))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.widget_3)
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_5.addWidget(self.radioButton_4, 3, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.widget_3)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(125, 14))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_5.addWidget(self.doubleSpinBox, 2, 4, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(parent=self.widget_3)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 1, 4, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.widget_3)
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_5.addWidget(self.radioButton_3, 2, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(parent=self.widget_3)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_5.addWidget(self.radioButton, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.widget_3)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_5.addWidget(self.radioButton_2, 1, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_36.setMinimumSize(QtCore.QSize(125, 14))
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 1, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(parent=self.widget_3)
        self.doubleSpinBox_2.setMaximum(0.5)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_5.addWidget(self.doubleSpinBox_2, 3, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_37.setMinimumSize(QtCore.QSize(125, 14))
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 2, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 3, 3, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.widget_3)
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_5.addWidget(self.radioButton_5, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 0, 4, 1, 1)
        self.verticalLayout_20.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lancer = QtWidgets.QPushButton(parent=self.widget_21, clicked= lambda:self.pricer(True))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        self.lancer.setFont(font)
        self.lancer.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #1e1e1e;\n"
"}\n"
"\n"
"QPushButton{\n"
"border: 1px solid;\n"
"}")
        self.lancer.setObjectName("lancer")
        self.verticalLayout_20.addWidget(self.lancer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_22.addWidget(self.widget_21)
        self.widget_25 = QtWidgets.QWidget(parent=self.page)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_26 = QtWidgets.QWidget(parent=self.widget_25)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_58 = QtWidgets.QLabel(parent=self.widget_26)
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/eye.svg"))
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_14.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(parent=self.widget_26)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_14.addWidget(self.label_59)
        self.verticalLayout_21.addWidget(self.widget_26, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_27 = QtWidgets.QWidget(parent=self.widget_25)
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_27)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        
        self.label_14 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 1, 3, 1, 1)
        self.verticalLayout_21.addWidget(self.widget_27)
        self.verticalLayout_22.addWidget(self.widget_25, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(parent=self.page_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setContentsMargins(-1, 16, -1, 16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_15.setMaximumSize(QtCore.QSize(83, 28))
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_15)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/activity.svg"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(parent=self.widget_15)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_7.addWidget(self.widget_15, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.widget_11)
        self.graphicsView.setObjectName("graphicsView")

       

        
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.widget_18 = QtWidgets.QWidget(parent=self.widget)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_12.setContentsMargins(-1, 16, -1, 16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_18)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout_2.setContentsMargins(-1, 15, -1, 15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.widget_17)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_2.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.widget_17)
        self.verticalLayout_8.addWidget(self.widget_18)
        self.horizontalLayout_6.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_5 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.home_1 = QtWidgets.QWidget(parent=self.widget_5)
        self.home_1.setObjectName("home_1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.home_1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_12 = QtWidgets.QWidget(parent=self.home_1)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setLineWidth(2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.verticalLayout_13.addWidget(self.widget_12)
        self.textEdit = QtWidgets.QTextEdit(parent=self.home_1)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_13.addWidget(self.textEdit)
        self.verticalLayout_17.addWidget(self.home_1)
        self.verticalLayout_18.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.mainmenu)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.optimization.setText(_translate("MainWindow", "Pricing"))
        self.contact.setText(_translate("MainWindow", "Graph"))
        self.deconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label.setText(_translate("MainWindow", "Binomial Model Option  Pricer"))
        self.label_4.setText(_translate("MainWindow", "Parameters of Pricing"))
        self.label_63.setText(_translate("MainWindow", "Volatilité"))
        self.label_65.setText(_translate("MainWindow", "Maturité"))
        self.label_55.setText(_translate("MainWindow", "Style"))
        self.label_57.setText(_translate("MainWindow", "Strike"))
        self.label_56.setText(_translate("MainWindow", "Prix"))
        self.label_64.setText(_translate("MainWindow", "Taux sans risque"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "call"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "put"))
        self.label_34.setText(_translate("MainWindow", " Model Set up"))
        self.label_19.setText(_translate("MainWindow", "Trinomial Model"))
        self.label_5.setText(_translate("MainWindow", "Binomial Model"))
        self.label_18.setText(_translate("MainWindow", "Generalize Binomial Model"))
        self.label_17.setText(_translate("MainWindow", "Flexible Binomial Model"))
        self.label_36.setText(_translate("MainWindow", "Facteur d\'inclinaison"))
        self.label_21.setText(_translate("MainWindow", "Black-Sholes Model"))
        self.label_37.setText(_translate("MainWindow", "Facteur d\'extension"))
        self.label_38.setText(_translate("MainWindow", "Libre probalité"))
        self.label_9.setText(_translate("MainWindow", "Type d\'option"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Européenne"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Américaine"))
        self.lancer.setText(_translate("MainWindow", "Lancer"))
        self.label_59.setText(_translate("MainWindow", " Model   Result "))
        self.label_16.setText(_translate("MainWindow", "-------"))
        self.label_61.setText(_translate("MainWindow", "------"))
        self.label_60.setText(_translate("MainWindow", "Delta"))
        self.label_2.setText(_translate("MainWindow", "Theta"))
        self.label_3.setText(_translate("MainWindow", "Gamma"))
        self.label_14.setText(_translate("MainWindow", "------"))
        self.label_62.setText(_translate("MainWindow", "Vega"))
        self.label_39.setText(_translate("MainWindow", "Option Price"))
        self.label_7.setText(_translate("MainWindow", "------"))
        self.label_40.setText(_translate("MainWindow", "-------"))
        self.label_8.setText(_translate("MainWindow", "Activity"))
        self.label_29.setText(_translate("MainWindow", "Binomial Model Option  Pricer Overviews"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Bienvenue dans l\'Interface de Pricing d\'Options </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Découvrez un outil puissant conçu pour vous aider à évaluer et comprendre les options américaines et européennes en utilisant le modèle binomial et Trinomial. Notre plateforme vous offre un accès facile et intuitif pour estimer les prix des options, visualiser des graphiques dynamiques et calculer les grecques clés, vous permettant ainsi de prendre des décisions éclairées dans le monde complexe de la finance.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Ce que vous pouvez faire :</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Évaluation Précise :</span> Notre modèle binomial de pointe vous permet d\'obtenir des estimations précises du prix des options en fonction de divers paramètres tels que la volatilité, le temps et le prix sous-jacent.</li>\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Visualisation Intuitive :</span> Explorez l\'évolution des prix d\'options au fil du temps grâce à des graphiques interactifs. Comprenez comment les variations des paramètres affectent la valeur des options.</li>\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Calcul des Grecques :</span> Mesurez la sensibilité de vos options aux mouvements du marché en calculant les grecques, y compris le delta, le gamma, le vega, le theta, et plus encore.</li>\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Personnalisation Complète :</span> Adaptez les paramètres des options pour correspondre à vos besoins spécifiques et obtenez des résultats sur mesure.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Démystifiez la complexité des options financières et prenez des décisions éclairées. Que vous soyez un investisseur, un trader ou un professionnel de la finance, notre interface de pricing d\'options est conçue pour répondre à vos besoins.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Prêt à commencer ? Explorez les fonctionnalités, effectuez des calculs précis et visualisez vos stratégies d\'options dès maintenant.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">Bienvenue dans le monde de la finance intelligente</span></p></body></html>"))

#############################################################################################
    def pricer(self,pressed):
        S=self.doubleSpinBox_6.value()
        K=self.doubleSpinBox_7.value()
        v=self.doubleSpinBox_8.value()
        r=self.doubleSpinBox_9.value()
        T=self.doubleSpinBox_10.value()
        style=self.comboBox_5.currentText()
        type=self.comboBox.currentText()
        qo=self.doubleSpinBox_2.value()
        l=self.spinBox.value()
        e=self.doubleSpinBox.value()
        p=75

        if(pressed):
          if(self.radioButton.isChecked()):
            if(type=="Européenne"):
              opt1=Option(S,K,T,r,v,style)
              self.label_40.setText(f"{round(opt1.payoffmultipl(p),3)} ")
              self.label_7.setText(f"{round(opt1.Delta(p),3)} ")
              self.label_61.setText(f"{abs(round(opt1.Gamma(p),3))} ")
              self.label_14.setText(f"{round(-opt1.Theta(p),3)} ")
              self.label_16.setText(f"{round(opt1.vega(p),3)}  ")

              """self.figure = Figure()
              self.canvas = FigureCanvas(self.figure)
              self.canvas.setSizePolicy(self.graphicsView.sizePolicy())

       
              ax = self.figure.add_subplot(111)
              ax.plot([1, 2, 3, 4, 5], [10, 5, 20, 10, 25])
              ax.set_title("Exemple de graphique Matplotlib")
              self.canvas.draw()

              self.graphicsView.setScene(QtWidgets.QGraphicsScene(self.graphicsView))
              #self.graphicsView.setSceneRect(self.graphicsView.rect())
              self.graphicsView.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft |QtCore.Qt.AlignmentFlag.AlignTop)
              self.graphicsView.setViewport(self.canvas)"""
              

            else:
              opt1=OptionAmericaine(S,K,T,r,v,style)
              self.label_40.setText(f"{round(opt1.payoffmultipl(p),3)} ")
              self.label_7.setText(f"{round(opt1.Delta(p),3)} ")
              self.label_61.setText(f"{abs(round(opt1.Gamma(p),3))} ")
              self.label_14.setText(f"{round(-opt1.Theta(p),3)} ")
              self.label_16.setText(f"{round(opt1.vega(p),3)} ")

        if(self.radioButton_2.isChecked()):
                opt1=Optionflexible(S,K,T,r,v,style)
                self.label_40.setText(f"{round(opt1.payoffmultipl(p,l),3)} ")
                self.label_7.setText(f"{round(opt1.Delta(p,l),3)} ")
                self.label_61.setText(f"{round(abs(opt1.Gamma(p,l)),3)} ")
                self.label_14.setText(f"{round(-opt1.Theta(p,l),3)} ")
                self.label_16.setText(f"{round(opt1.vega(p,l),3)} ")

        if(self.radioButton_3.isChecked()):
            opt1=Optiongeneralise(S,K,T,r,v,style)
            self.label_40.setText(f"{round(opt1.payoffmultipl(p,e),3)} ")
            self.label_7.setText(f"{round(opt1.Delta(p,e),3)} ")
            self.label_61.setText(f"{abs(round(opt1.Gamma(p,e),3))} ")
            self.label_14.setText(f"{round(-opt1.Theta(p,e),3)} ")
            self.label_16.setText(f"{round(opt1.vega(p,e),3)} ")
              
        if(self.radioButton_4.isChecked()):
            if(type=="Européenne"):
              opt1=OptionTrinomial(S,K,T,r,v,style)
              self.label_40.setText(f"{round(opt1.payoffmultipl(p,qo),3)} ")
              self.label_7.setText(f"{round(opt1.Delta(p,qo),3)} ")
              self.label_61.setText(f"{abs(round(opt1.Gamma(p,qo),3))} ")
              self.label_14.setText(f"{round(-opt1.Theta(p,qo),3)} ")
              self.label_16.setText(f"{round(opt1.vega(p,qo),3)} ")

            else:
              opt1=AmericanOptionTrinomial(S,K,T,r,v,style)
              self.label_40.setText(f"{round(opt1.payoffmultipl(p,qo),3)} ")#
              self.label_7.setText(f"{round(opt1.Delta(p,qo),3)} ")
              self.label_61.setText(f"{abs(round(opt1.Gamma(p,qo),3))} ")
              self.label_14.setText(f"{-round(opt1.Theta(p,qo),3)} ")
              self.label_16.setText(f"{round(opt1.vega(p,qo),3)} ")
        
        if(self.radioButton_5.isChecked()):
            self.label_40.setText(f"{round(black_scholes(S,K,T,r,v,style),3)} ")
            self.label_7.setText(f"{round(delta(S,K,T,r,v,style),3)} ")
            self.label_61.setText(f"{round(gamma(S,K,T,r,v,style),3)} ")
            self.label_14.setText(f"{round(theta(S,K,T,r,v,style),3)} ")
            self.label_16.setText(f"{round(vega(S,K,T,r,v,style),3)} ")
            #self.label_35.setText(f"{round(rho(S,K,T,r,v,style))} ") 
            
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
