# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hp\Documents\Python_Scripts\Pyqt_programme\tuto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
from scipy.stats import norm
import math as ma

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 181, 251))
        self.groupBox.setObjectName("groupBox")

        self.price = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.price.setGeometry(QtCore.QRect(80, 20, 81, 22))
        self.price.setRange(0,500)
        self.price.setObjectName("price")
        self.price.setSuffix(" Unit")
        self.price.valueChanged.connect(self.prix_St_norm)


        self.freerate = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.freerate.setGeometry(QtCore.QRect(80, 140, 81, 22))
        self.freerate.setObjectName("freerate")
        self.freerate.setRange(0,100)
        self.freerate.setSuffix(" %")
        self.freerate.valueChanged.connect(self.prix_St_norm)


        self.strike = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.strike.setGeometry(QtCore.QRect(80, 50, 81, 21))
        self.strike.setObjectName("strike")
        self.strike.setValue(1)
        self.strike.setRange(0,500)
        self.strike.setSuffix(" Unit")
        self.strike.valueChanged.connect(self.prix_St_norm)


        self.time = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.time.setGeometry(QtCore.QRect(80, 80, 81, 22))
        self.time.setValue(1)
        self.time.setRange(0.01,15)
        self.time.setSingleStep(0.1)
        self.time.setObjectName("time")
        self.time.setSuffix(" years")
        self.time.valueChanged.connect(self.prix_St_norm)

        self.volatility = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.volatility.setGeometry(QtCore.QRect(80, 110, 81, 22))
        self.volatility.setObjectName("volatity")
        self.volatility.setValue(1)
        self.volatility.setRange(0,100)
        self.volatility.setSuffix(" %")
        self.volatility.valueChanged.connect(self.prix_St_norm)

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 51, 20))
        self.label_5.setObjectName("label_5")

        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 40, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_6.setObjectName("label_6")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 20, 561, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(220, 71, 331, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 50, 111, 20))
        self.label_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 10, 401, 20))
        self.label_8.setObjectName("label_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 240, 331, 80))
        self.groupBox_2.setObjectName("groupBox_2")

        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(170, 20, 131, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(170, 46, 131, 20))
        self.label_12.setObjectName("label_12")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.prix_St_norm()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.prix_St_norm)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Paramètres"))
        self.label.setText(_translate("MainWindow", "Price (So)"))
        self.label_2.setText(_translate("MainWindow", "Strike(K)"))
        self.label_3.setText(_translate("MainWindow", "Time(T)"))
        self.label_4.setText(_translate("MainWindow", "Volatility"))
        self.label_5.setText(_translate("MainWindow", "free rate"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Call"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Put"))
        self.label_6.setText(_translate("MainWindow", "Option Style"))
        self.label_7.setText(_translate("MainWindow", "Graphics View"))
        self.label_8.setText(_translate("MainWindow", "PRICING DES OPTIONS EUROPEENE PAR SIMULATION DE MONTECARLO"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Resultat"))
        self.label_9.setText(_translate("MainWindow", "MonteCarlo Price"))
        self.label_10.setText(_translate("MainWindow", "BlackSholes Price"))
        self.label_11.setText(_translate("MainWindow", "---"))
        self.label_12.setText(_translate("MainWindow", "---"))
    
    def prix_St_norm(self):
       const=1000
       alpha=0.05
       So= self.price.value()
       K= self.strike.value()
       T= self.time.value()
       sigma= self.volatility.value()/100
       r=self.freerate.value()/100
       style= self.comboBox.currentText()
       browm1=  np.random.normal(0,1,const)
       St1=np.zeros((const))
       St2=np.zeros((const))
       for j in range(const):
          St1[j] = So*ma.exp((r-(sigma**2)/2)*T + sigma*ma.sqrt(T)*browm1[j])
          St2[j]= So*ma.exp((r-(sigma**2)/2)*T - sigma*ma.sqrt(T)*browm1[j])   
       
       payoff=np.ones(const)
       if (style=="Call"):
         for i in range(const):
          payoff[i]=((max((St1[i]-K),0)+ (max((St2[i]-K),0)))*ma.exp(-r*T))/2
        
          self.label_11.setText(str(round(np.mean(payoff),2))+" +/- "+str(round((norm.cdf(alpha)*np.std(payoff))/np.sqrt(const),3)))
       if(style=='Put'):
          for i in range(const):       
            payoff[i]=((max(K-(St1[i][-1]),0))*ma.exp(-r*T)+ (max(K-(St2[i][-1]),0))*ma.exp(-r*T))/2
       
          self.label_11.setText(str(round(np.mean(payoff),2))+" +/- "+str(round((norm.cdf(alpha)*np.std(payoff))/np.sqrt(const),3)))


       d1 = (np.log(So/K) + (r  + sigma**2/2)*T) / sigma*np.sqrt(T)
       d2 = d1 - sigma* np.sqrt(T)
       if (style=='Call'):
          self.label_12.setText(str(So * norm.cdf(d1)  - K * np.exp(-r*T)*norm.cdf(d2)))
       if(style=='Put'):
          self.label_12.setText(str(K * np.exp(-r*T)*norm.cdf(-d2)-So * norm.cdf(-d1)))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
