# Form implementation generated from reading ui file 'C:\Users\hp\Documents\Python_Scripts\Pyqt_programme\pfa.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QPropertyAnimation
from fonctions import *

import fonctions
from datetime import datetime
import math as ma

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 555)
        MainWindow.setStyleSheet("*{\n"
"border:none;\n"
"background-color: transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"\n"
"\n"
"}\n"
"\n"
"#mainmenu{\n"
"    background-color: #FFE436;\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color: white;\n"
"}\n"
"#subsidebar{\n"
"background-color:#16191d;\n"
"}\n"
"#widget_4{\n"
"background-color:#16191d;\n"
"}\n"
"\n"
"#subsidebar QPushButton{\n"
"text-align: left;\n"
"padding:2px 5px;\n"
"color:#fff;\n"
"}\n"
"#subsidebar QPushButton :hover{\n"
"padding:2px 5px;\n"
"background-color:#FFE436;\n"
"}\n"
"\n"
"#page_3{\n"
"background-color: white;\n"
"}\n"
"\n"
"#page_2{\n"
"background-color: white;\n"
"}\n"
"\n"
"#page{\n"
"background-color: white;\n"
"}\n"
"\n"
"#lineEdit_3{\n"
"border-radius: 3px;\n"
"border: 2px solid #000;\n"
"}\n"
"#widget_3{\n"
"border:2px solid;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"#widget_8{\n"
"background-color: #aaffff;\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_10{\n"
"background-color: #55ff7f;\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"#widget_7{\n"
"background-color: #DDD;\n"
"border: 2px solid #000;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_9{\n"
"background-color: #FFE436;\n"
"border: 2px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_15{\n"
"background-color: #FFE436;\n"
"border: 2px solid ;\n"
"border-radius: 5px;\n"
"}\n"
"#widget_11{\n"
"background-color: rgb(235, 157, 235);\n"
"border: 2px solid ;\n"
"border-radius:5px;\n"
"}\n"
"#widget_17{\n"
"border: 2px solid gray ;\n"
"border-radius:5px;\n"
"}\n"
"#widget_19{\n"
"border-style: ;\n"
"border: 2px groove gray ;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#widget_21{\n"
"border: 2px groove gray ;\n"
"border-radius:5px;\n"
"}\n"
"#widget_20{\n"
"background-color: #FFE436;\n"
"border: 1px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_22{\n"
"background-color: #FFE436;\n"
"border: 1px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_26{\n"
"background-color: #FFE436;\n"
"border: 1px solid ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_6{\n"
"border: 2px groove gray ;\n"
"border-radius: 10px;\n"
"}\n"
"#widget_18{\n"
"border: 2px groove gray ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#widget_25{\n"
"border: 2px groove gray ;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#widget_12{\n"
"background-color:  #FFE436;\n"
"border: 2px solid l;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}\n"
"#widget_14{\n"
"background-color: #FFE436;\n"
"border: 2px solid ;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}\n"
"\n"
"#home_1{\n"
"border: 2px solid black ;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}\n"
"#label_43{\n"
"border: 2px solid black ;\n"
"border-top:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subsidebar = QtWidgets.QWidget(parent=self.sidebar)
        self.subsidebar.setObjectName("subsidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subsidebar)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.subsidebar)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu = QtWidgets.QPushButton(parent=self.frame)
        self.menu.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"\n"
"}")
        self.menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/menu.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.menu.setIcon(icon)
        self.menu.setObjectName("menu")
        self.menu.clicked.connect(lambda: self.toggleMenu( ))
        
        self.verticalLayout_3.addWidget(self.menu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_2 = QtWidgets.QFrame(parent=self.subsidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.home = QtWidgets.QPushButton(parent=self.frame_2)
        self.home.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/home.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.home.setIcon(icon1)
        self.home.setObjectName("home")
        self.home.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        self.verticalLayout_4.addWidget(self.home)
        self.portfolio = QtWidgets.QPushButton(parent=self.frame_2)
        self.portfolio.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/pocket.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.portfolio.setIcon(icon2)
        self.portfolio.setObjectName("portfolio")
        self.portfolio.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_3))
        
        self.verticalLayout_4.addWidget(self.portfolio)
        self.optimization = QtWidgets.QPushButton(parent=self.frame_2)
        self.optimization.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/settings.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.optimization.setIcon(icon3)
        self.optimization.setObjectName("optimization")
        self.verticalLayout_4.addWidget(self.optimization)
        self.optimization.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page))
        self.propos = QtWidgets.QPushButton(parent=self.frame_2)
        self.propos.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/share-2.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.propos.setIcon(icon4)
        self.propos.setObjectName("propos")
        self.propos.clicked.connect( self.page_un)
        self.verticalLayout_4.addWidget(self.propos)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(parent=self.subsidebar)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.contact = QtWidgets.QPushButton(parent=self.frame_3)
        self.contact.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/phone.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.contact.setIcon(icon5)
        self.contact.setObjectName("contact")
        self.verticalLayout_5.addWidget(self.contact)
        self.deconnect = QtWidgets.QPushButton(parent=self.frame_3)
        self.deconnect.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #FFE436;\n"
"padding: 2px 5px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\feather (1)/log-out.svg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.deconnect.setIcon(icon6)
        self.deconnect.setObjectName("deconnect")
        self.verticalLayout_5.addWidget(self.deconnect)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.subsidebar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.sidebar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.mainmenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainmenu.setObjectName("mainmenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainmenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.mainmenu)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\Image/oracle capital.jpg"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.searchframe = QtWidgets.QFrame(parent=self.frame_4)
        self.searchframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.searchframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.searchframe.setObjectName("searchframe")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.searchframe)
        self.horizontalLayout_2.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.searchframe)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(32775)
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.widget_3 = QtWidgets.QWidget(parent=self.searchframe)
        self.widget_3.setStyleSheet("#QLineEdit{\n"
"background: transparent;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/search.svg"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_3.addWidget(self.searchframe)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainmenu)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_19 = QtWidgets.QWidget(parent=self.page)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_20 = QtWidgets.QWidget(parent=self.widget_19)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_10.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_20)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/target.svg"))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_20)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.verticalLayout_19.addWidget(self.widget_20, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget_19)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        self.verticalLayout_19.addWidget(self.tableWidget)
        self.verticalLayout_22.addWidget(self.widget_19)
        self.widget_21 = QtWidgets.QWidget(parent=self.page)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_22 = QtWidgets.QWidget(parent=self.widget_21)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_11.setContentsMargins(3, 2, 3, 1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_32 = QtWidgets.QLabel(parent=self.widget_22)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/settings.svg"))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_34 = QtWidgets.QLabel(parent=self.widget_22)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_11.addWidget(self.label_34, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_20.addWidget(self.widget_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_23 = QtWidgets.QWidget(parent=self.widget_21)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_36 = QtWidgets.QLabel(parent=self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_12.addWidget(self.label_36)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setAccelerated(True)
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMaximum(1000000000.0)
        self.doubleSpinBox.setSingleStep(1000.0)
        self.doubleSpinBox.setProperty("value", 100000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox)
        self.label_37 = QtWidgets.QLabel(parent=self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_12.addWidget(self.label_37)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(parent=self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setMaximum(6.0)
        self.doubleSpinBox_2.setProperty("value", 3.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_20.addWidget(self.widget_23)
        self.lancer = QtWidgets.QPushButton(parent=self.widget_21,clicked= lambda:self.optimiser(True))
       # self.lancer.clicked.connect( self.optimiser(True))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        self.lancer.setFont(font)
        self.lancer.setStyleSheet("QPushButton:hover\n"
"{\n"
"color:white;\n"
"background-color: #1e1e1e;\n"
"}\n"
"\n"
"QPushButton{\n"
"border: 1px solid;\n"
"}")
        self.lancer.setObjectName("lancer")
        self.verticalLayout_20.addWidget(self.lancer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_24 = QtWidgets.QWidget(parent=self.widget_21)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_38 = QtWidgets.QLabel(parent=self.widget_24)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_13.addWidget(self.label_38)
        self.action_value = QtWidgets.QLabel(parent=self.widget_24)
        self.action_value.setObjectName("action_value")
        self.horizontalLayout_13.addWidget(self.action_value)
        self.label_54 = QtWidgets.QLabel(parent=self.widget_24)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_13.addWidget(self.label_54)
        self.bond_value = QtWidgets.QLabel(parent=self.widget_24)
        self.bond_value.setObjectName("bond_value")
        self.horizontalLayout_13.addWidget(self.bond_value)
        self.label_55 = QtWidgets.QLabel(parent=self.widget_24)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_13.addWidget(self.label_55)
        self.etf_value = QtWidgets.QLabel(parent=self.widget_24)
        self.etf_value.setObjectName("etf_value")
        self.horizontalLayout_13.addWidget(self.etf_value)
        self.label_56 = QtWidgets.QLabel(parent=self.widget_24)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_13.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(parent=self.widget_24)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_13.addWidget(self.label_57)
        self.verticalLayout_20.addWidget(self.widget_24)
        self.verticalLayout_22.addWidget(self.widget_21)
        self.widget_25 = QtWidgets.QWidget(parent=self.page)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_26 = QtWidgets.QWidget(parent=self.widget_25)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_58 = QtWidgets.QLabel(parent=self.widget_26)
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/eye.svg"))
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_14.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(parent=self.widget_26)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_14.addWidget(self.label_59)
        self.verticalLayout_21.addWidget(self.widget_26, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_27 = QtWidgets.QWidget(parent=self.widget_25)
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_27)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_61 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(parent=self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 1, 1, 1)
        self.verticalLayout_21.addWidget(self.widget_27)
        self.verticalLayout_22.addWidget(self.widget_25, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(parent=self.page_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setContentsMargins(-1, 16, -1, 16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_15)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/activity.svg"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(parent=self.widget_15)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_7.addWidget(self.widget_15, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_16 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_8.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/dollar-sign.svg"))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_35 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_9.addWidget(self.label_35, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_8.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/gift.svg"))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_33 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_10.addWidget(self.label_33, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_8.addWidget(self.widget_8, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/percent.svg"))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_31 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_11.addWidget(self.label_31, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_8.addWidget(self.widget_10)
        self.verticalLayout_7.addWidget(self.widget_16)
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout.setObjectName("gridLayout")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 1, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.verticalLayout_8.addWidget(self.widget_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.widget_18 = QtWidgets.QWidget(parent=self.widget)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_12.setContentsMargins(-1, 16, -1, 16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_18)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_9.setContentsMargins(1, 3, 2, 3)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_23 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Documents\\Python_Scripts\\Pyqt_programme\\icon/briefcase.svg"))
        self.label_23.setScaledContents(False)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.verticalLayout_12.addWidget(self.widget_9, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_18)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout_2.setContentsMargins(-1, 15, -1, 15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(parent=self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 0, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(parent=self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 1, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(parent=self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(True)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 1, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(parent=self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(parent=self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 2, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 2, 3, 1, 1)
        self.verticalLayout_12.addWidget(self.widget_17)
        self.verticalLayout_8.addWidget(self.widget_18)
        self.horizontalLayout_6.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_5 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.home_1 = QtWidgets.QWidget(parent=self.widget_5)
        self.home_1.setObjectName("home_1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.home_1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_12 = QtWidgets.QWidget(parent=self.home_1)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(13)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setLineWidth(2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.verticalLayout_13.addWidget(self.widget_12)
        self.textEdit = QtWidgets.QTextEdit(parent=self.home_1)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_13.addWidget(self.textEdit)
        self.verticalLayout_17.addWidget(self.home_1)
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_13)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_39 = QtWidgets.QLabel(parent=self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_16.addWidget(self.label_39)
        self.verticalLayout_15.addWidget(self.widget_14)
        self.label_40 = QtWidgets.QLabel(parent=self.widget_13)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_15.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(parent=self.widget_13)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_15.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(parent=self.widget_13)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_15.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(parent=self.widget_13)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_15.addWidget(self.label_43)
        self.verticalLayout_17.addWidget(self.widget_13)
        self.verticalLayout_18.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.mainmenu)
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 190, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.portfolio.setText(_translate("MainWindow", "My Portfolio"))
        self.optimization.setText(_translate("MainWindow", "Optimization"))
        self.propos.setText(_translate("MainWindow", "A Propos"))
        self.contact.setText(_translate("MainWindow", "Contact"))
        self.deconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Rechercher votre actif"))
        self.label_4.setText(_translate("MainWindow", " Présentation des actifs du mois "))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Actions"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Obligations"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ETF"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Commodités"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Benchmark"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Poids"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_34.setText(_translate("MainWindow", " Portfolio Set up"))
        self.label_36.setText(_translate("MainWindow", "Montant "))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", " Dhs"))
        self.label_37.setText(_translate("MainWindow", "Durée"))
        self.doubleSpinBox_2.setSuffix(_translate("MainWindow", " mois"))
        self.lancer.setText(_translate("MainWindow", "Lancer"))
        self.label_38.setText(_translate("MainWindow", "Action:"))
        self.action_value.setText(_translate("MainWindow", "-----"))
        self.label_54.setText(_translate("MainWindow", "Bonds"))
        self.bond_value.setText(_translate("MainWindow", "----"))
        self.label_55.setText(_translate("MainWindow", "ETF"))
        self.etf_value.setText(_translate("MainWindow", "-----"))
        self.label_56.setText(_translate("MainWindow", "Commodité"))
        self.label_57.setText(_translate("MainWindow", "-----"))
        self.label_59.setText(_translate("MainWindow", " Portfolio  Expectation"))
        self.label_61.setText(_translate("MainWindow", "------"))
        self.label_60.setText(_translate("MainWindow", "Expected return"))
        self.label_62.setText(_translate("MainWindow", "Predicted CVar "))
        self.label_2.setText(_translate("MainWindow", "Bêta"))
        self.label_3.setText(_translate("MainWindow", "Predicted Var "))
        self.label_7.setText(_translate("MainWindow", "------"))
        self.label_14.setText(_translate("MainWindow", "------"))
        self.label_16.setText(_translate("MainWindow", "-------"))
        self.label_8.setText(_translate("MainWindow", "Activity"))
        self.label_10.setText(_translate("MainWindow", "Total Value"))
        self.label_35.setText(_translate("MainWindow", "----"))
        self.label_12.setText(_translate("MainWindow", "Profit & Lost"))
        self.label_33.setText(_translate("MainWindow", "---"))
        self.label_15.setText(_translate("MainWindow", "Rendement"))
        self.label_31.setText(_translate("MainWindow", "----"))
        self.label_20.setText(_translate("MainWindow", "Value At Risk"))
        self.label_45.setText(_translate("MainWindow", "----"))
        self.label_44.setText(_translate("MainWindow", "---"))
        self.label_22.setText(_translate("MainWindow", "Conditionnal Value At Risk"))
        self.label_24.setText(_translate("MainWindow", "Outils D\'analyse de performance"))
        self.label_26.setText(_translate("MainWindow", "Beta:"))
        self.label_48.setText(_translate("MainWindow", "----"))
        self.label_46.setText(_translate("MainWindow", "Max Drawdown"))
        self.label_49.setText(_translate("MainWindow", "----"))
        self.label_27.setText(_translate("MainWindow", "Treynor:"))
        self.label_50.setText(_translate("MainWindow", "----"))
        self.label_47.setText(_translate("MainWindow", "Sortino"))
        self.label_53.setText(_translate("MainWindow", "----"))
        self.label_25.setText(_translate("MainWindow", "Sharpe Rate"))
        self.label_51.setText(_translate("MainWindow", "----"))
        self.label_28.setText(_translate("MainWindow", "Alpha Jensen"))
        self.label_52.setText(_translate("MainWindow", "----"))
        self.label_29.setText(_translate("MainWindow", "Portfolio Monte Carlo Simulation Overview"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Bienvenue sur notre dashboard de gestion de portefeuille basé sur la méthode de Monte Carlo !</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Notre outil vous permet de prendre des décisions éclairées en matière d\'investissement en utilisant une approche statistique avancée. La méthode de Monte Carlo, reconnue pour sa précision et sa fiabilité, est utilisée pour simuler de multiples scénarios afin de prédire les performances potentielles de votre portefeuille.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Notre dashboard vous offre également des fonctionnalités avancées telles que l\'optimisation des allocations d\'actifs, la gestion du risque et la comparaison de différents scénarios d\'investissement. Vous pouvez explorer différentes stratégies et ajuster les paramètres pour trouver la combinaison optimale qui correspond à vos objectifs financiers.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nous sommes ravis de vous accompagner,chévronné ou débutant, dans votre parcours financier et de vous offrir une perspective réaliste et probabiliste sur la performance de votre portefeuille. N\'hésitez pas à explorer les fonctionnalités de notre dashboard et à tirer parti de l\'analyse approfondie qu\'il offre.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Bienvenue Chez Oracle Capital, où la précision statistique rencontre l\'intelligence financière.</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "Portfolio Optimization Configuration"))
        self.label_40.setText(_translate("MainWindow", "Portfolio Type :                                                                                  Mixed        "))
        self.label_41.setText(_translate("MainWindow", "Time period :                                                                                      Daily "))
        self.label_42.setText(_translate("MainWindow", "Duration :                                                                                            Three months "))
        self.label_43.setText(_translate("MainWindow", "Optimisation method:                                                      Mean Variance Maximize Sharpe Ratio"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.menu_enable=0

################################################################################
    def page_un(self):
      tickers=["GOOGL", "MSFT", "GC=F", "TSLA",'AAPL', "BABA", "^IXIC", "^TNX"]
      date_start="2023-04-01"
      raw_data= data_(tickers,date_start,datetime.today().strftime('%Y-%m-%d'))
      raw_data= raw_data.drop(raw_data.index[-1])
      return_data=data_returns(tickers,date_start,datetime.today().strftime('%Y-%m-%d'))
      return_data=return_data.drop(return_data.index[-1])
      rm=data_returns(["^SP500-40"],date_start,datetime.today().strftime('%Y-%m-%d'))
      rm=rm.drop(rm.index[-1])
      weights =np.ones(len(tickers))
      st=(Rp(raw_data.iloc[-1], weights))
      so=Rp(raw_data.iloc[0], weights)
      var_his=var_historic(raw_data,weights/10,0.95)
      cvar_his=cvar_historic(raw_data,weights/10,0.95)[0]
      baita=beta(rm,Rp(return_data,weights))
      rf=0.006
      alpha_jen=alphaJensen(Rp(return_data,weights),rm,rf)
      treyor=treynor(Rp(return_data,weights),rm,rf)
      rate_sharp=sharpeRate(Rp(return_data,weights),rf)
      sortin=sortino(Rp(return_data,weights),rf)
      mdd=drawdown(Rp(raw_data, weights))

      self.label_35.setText(f"{round(st)} $")
      self.label_33.setText(f"{round(st-so)} $")
      self.label_31.setText(f"{round(((st-so)/so)*100,1)} %")
      self.label_44.setText(f"{round(var_his,3)} ")
      self.label_45.setText(f"{round(cvar_his,3)} ")
    
      self.label_48.setText(f"{round(baita,5)} ")
      self.label_49.setText(f"{round(mdd,5)} ")
      self.label_50.setText(f"{round(treyor,5)} ")
      self.label_51.setText(f"{round(rate_sharp,5)} ")
      self.label_52.setText(f"{round(alpha_jen,5)} ")
      self.label_53.setText(f"{round(sortin,5)} ")
      
########################################################################################

    def optimiser(self,pressed):
      tick=["NMIH",  "MKTX",'CRVL',"FANH","TW",'SNEX', " HGBL"]
      start_date="2023-01-01"
      end_date="2023-04-01"
      rm=return_sim(["^SP500-40"],start_date,end_date)
      datan=return_sim(tick,start_date,end_date)
      weights=ponderation()
      if(pressed):
          
          value= self.doubleSpinBox.value()
          
          portfolio=PortfolioStat(datan, sim=100000)
          rf=0.006
          maxSR=MaxSharpeRate(portfolio, rf)
          sr =sharpeRate(Rp(datan,weights),0)
          baita=beta(rm,Rp(datan,weights))
          var_his=var_historic_pred(datan,weights,0.05)
          cvar_his=cvar_historic_pred(datan,weights,0.05)[0]
          sortin=sortino(Rp(datan,weights),rf)
          poid=[1,0,0,0]
          self.action_value.setText(f"{round(value*poid[0])} $ ")
          self.bond_value.setText(f"{round(value*poid[1])} $ ")
          self.etf_value.setText(f"{round(value*poid[2])}  $")
          self.label_57.setText(f"{round(value*poid[3])} $")
          self.label_60.setText(f"Expected return: {round(((1+np.mean(Rp(datan,weights)))**63-1)*100,2)} %")
          self.label_7.setText(f"Expected risk: {round(np.std(Rp(datan,weights))*ma.sqrt(63)*100,5)} %")
          self.label_14.setText(f"Expected Max Sharpe rate : {sr}")
          self.label_2.setText(f"Beta: {round(baita,3)} ")
          self.label_61.setText(f"Sortino Ratio: {round(sortin,3)} ")
          self.label_3.setText(f"Predicted Var: {round(var_his,3)} % ")
          self.label_62.setText(f"Predicted CVar: {round(cvar_his,3)} % ")



          
        
    
    


#####################################################################################
    def toggleMenu(self ):
         if self.menu_enable==0:
            # ANIMATION
            self.animation1 = QPropertyAnimation(self.sidebar, b"minimumWidth")
            self.animation1.setDuration(400)
            self.animation1.setStartValue(49)
            self.animation1.setEndValue(110)
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()

            self.animation2 = QPropertyAnimation(self.sidebar, b"maximumWidth")
            self.animation2.setDuration(400)
            self.animation2.setStartValue(49)
            self.animation2.setEndValue(110)
            self.animation2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation2.start()
            self.menu_enable=1






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
